### ISSUE TITLE
关于WriteWithPointer和AddKeyInfo的疑问

### ISSUE THREAD

**Issue by MaggieNgWu** [vntchain/bottle#21]
1. Bottle中“WriteWithPointer”这个指令是何时加入的？
Bottle在构造函数中加入了Key的初始化。 从.compile.c的文件中可以读出来。可在将.compile.c编译程.wasm后, 却多了“WriteWithPointer”的指令.  对应的代码在哪里呢？

2. 合约数据如何存入状态树中？
合约数据存储是通过什么方式，哪几个指令实现的呢？

**Comment by ooozws** [comment]
> 1. Bottle中“WriteWithPointer”这个指令是何时加入的？
>    Bottle在构造函数中加入了Key的初始化。 从.compile.c的文件中可以读出来。可在将.compile.c编译程.wasm后, 却多了“WriteWithPointer”的指令.  对应的代码在哪里呢？
> 2. 合约数据如何存入状态树中？
>    合约数据存储是通过什么方式，哪几个指令实现的呢？

vntchain合约中的状态变量KEY会对链上的数据自动进行读写，具体实现是这样的：
bottle会解析合约中的KEY语句并将KEY分解成一个多叉树,对于简单的类型比如string,address等，tree按照
root->指针地址->KEY的类型来构建
对于复杂类型，比如struct,需要分解struct内的元素

```c
KEY string a; 
KEY int32 b;
KEY struct{
   string a;
   int32 b; 
} c;
```

对于上面三个KEY，构建出来的tree是这样的

```
root — a的指针地址和类型pointer — a的指针地址和类型string
    |— b的指针地址和类型pointer — b的指针地址和类型int32
    |— c的指针地址和类型pointer — c.a的指针地址和类型string 
                             |— c.b的指针地址和类型int32
```

类型定义如下

```c
//二次编译时用到的类型标记
#define TY_INT32 1
#define TY_INT64 2
#define TY_UINT32 3
#define TY_UINT64 4
#define TY_UINT256 5
#define TY_STRING 6
#define TY_ADDRESS 7
#define TY_BOOL 8
#define TY_POINTER 9
```

之后bottle通过addkeyinfo方法在合约代码中插入tree的信息

```c
AddKeyInfo( &a, 6, &a, 9, false);
AddKeyInfo( &b, 1, &b, 9, false);
AddKeyInfo( &c.a, 6, &c, 9, false);
AddKeyInfo( &c.a, 6, &c.a, 9, false);
AddKeyInfo( &c.b, 1, &c, 9, false);
AddKeyInfo( &c.b, 1, &c.b, 9, false);
```

通过AddKeyInfo，在gvnt的wavm中会构建keyinfo的字典，参考代码

```
func (ef *EnvFunctions) AddKeyInfo(proc *exec.WavmProcess, valAddr, valType, keyAddr, keyType, isArrayIndex uint64) 
```

同时，wavm在构建wasm module的时候，会对module进行编译，编译过程中会对
ops.I32Load, ops.I64Load, ops.F32Load, ops.F64Load, ops.I32Load8s, ops.I32Load8u, ops.I32Load16s, ops.I32Load16u, ops.I64Load8s, ops.I64Load8u, ops.I64Load16s, ops.I64Load16u, ops.I64Load32s, ops.I64Load32u的前面插入call ReadWithPointer 的操作，用于在load状态变量之前先从链上读取数据，
对
ops.I32Store, ops.I64Store, ops.F32Store, ops.F64Store, ops.I32Store8, ops.I32Store16, ops.I64Store8, ops.I64Store16, ops.I64Store32的后面插入call WriteWithPointer,用于在store状态变量之后将数据存于链上。代码参考

```golang
func Compile(disassembly []disasm.Instr, module *wasm.Module, mutable Mutable) ([]byte, []*vnt.BranchTable)
```

之后，ReadWithPointer和WriteWithPointer会根据之前构建的keyinfo字典判断某个需要操作的内存是否在字典中，如果属于字典中的地址，则表明这个地址为KEY，就需要对链上数据进行读或者写

**Comment by MaggieNgWu** [comment]
明白了， 谢谢大神， 解释得好详细。
